// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDB(arg1) {
  return window['go']['main']['App']['ConnectDB'](arg1);
}

export function ConnectDBConfig(arg1) {
  return window['go']['main']['App']['ConnectDBConfig'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExecuteQueryWithColumns(arg1) {
  return window['go']['main']['App']['ExecuteQueryWithColumns'](arg1);
}

export function ExportSqlDump(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportSqlDump'](arg1, arg2, arg3);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetColumns(arg1) {
  return window['go']['main']['App']['GetColumns'](arg1);
}

export function GetDatabases() {
  return window['go']['main']['App']['GetDatabases']();
}

export function GetDatabasesForConfig(arg1) {
  return window['go']['main']['App']['GetDatabasesForConfig'](arg1);
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetTableStats(arg1, arg2) {
  return window['go']['main']['App']['GetTableStats'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function GetViews(arg1) {
  return window['go']['main']['App']['GetViews'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveExcelFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExcelFile'](arg1, arg2);
}

export function SaveExcelFromJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveExcelFromJSON'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SyncDatabase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SyncDatabase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestConnectionConfig(arg1) {
  return window['go']['main']['App']['TestConnectionConfig'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
