// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectDB(arg1:string):Promise<void>;

export function ConnectDBConfig(arg1:main.DBConfig):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string):Promise<Array<Record<string, any>>>;

export function ExecuteQueryWithColumns(arg1:string):Promise<main.QueryResult>;

export function ExportSqlDump(arg1:main.DBConfig,arg2:Array<string>,arg3:string):Promise<string>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetColumns(arg1:string):Promise<Array<main.ColumnMeta>>;

export function GetDatabases():Promise<Array<string>>;

export function GetDatabasesForConfig(arg1:main.DBConfig):Promise<Array<string>>;

export function GetProcessList():Promise<Array<Record<string, any>>>;

export function GetSavedConnections():Promise<Array<main.DBConfig>>;

export function GetTableStats(arg1:main.DBConfig,arg2:string):Promise<Array<main.TableStat>>;

export function GetTables(arg1:string):Promise<Array<main.TableMeta>>;

export function GetViews(arg1:string):Promise<Array<main.ViewMeta>>;

export function KillProcess(arg1:number):Promise<void>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SaveConnection(arg1:main.DBConfig):Promise<void>;

export function SaveExcelFile(arg1:string,arg2:string):Promise<string>;

export function SaveExcelFromJSON(arg1:string,arg2:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function SyncDatabase(arg1:main.DBConfig,arg2:string,arg3:main.DBConfig,arg4:string,arg5:string,arg6:Array<string>):Promise<Array<main.MigrationCheckRow>>;

export function TestConnection(arg1:string):Promise<void>;

export function TestConnectionConfig(arg1:main.DBConfig):Promise<void>;

export function UpdateConnection(arg1:main.DBConfig):Promise<void>;
